In [1]:
import time
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
%matplotlib notebook
plt.rcParams['animation.html'] = 'jshtml'

In [3]:
eye_data = pd.read_csv("eyetracking_data_1.csv")
eye_data.head(5)

,raw_timestamp,relative_to_video_first_frame_timestamp,focus_distance,frame_number,stability,status,gaze_forward_x,gaze_forward_y,gaze_forward_z,gaze_origin_x,...,right_forward_x,right_forward_y,right_forward_z,right_origin_x,right_origin_y,right_origin_z,right_pupil_size,right_status,right_projected_x,right_projected_y
0,1000002221705113400,45677400,2.000000,216712,0.0,2,0.066119,-0.114159,0.991260,0.0,...,0.054033,-0.095844,0.993929,0.032887,0.0,0.0,0.177752,2,-0.106161,-0.094754
1,1000002221715228600,55792600,0.921631,216713,0.0,2,0.128154,-0.122562,0.984152,0.0,...,0.105817,-0.105854,0.988735,0.032887,0.0,0.0,0.177144,2,-0.045893,-0.105192
2,1000002221725212900,65776900,0.541743,216714,0.0,2,0.178060,-0.128675,0.975570,0.0,...,0.143840,-0.099788,0.984557,0.032887,0.0,0.0,0.178652,2,-0.001186,-0.099568
3,1000002221735257200,75821200,0.575953,216715,0.0,2,0.179317,-0.135090,0.974472,0.0,...,0.140024,-0.110180,0.983999,0.032887,0.0,0.0,0.176514,2,-0.005533,-0.110006
4,1000002221745206900,85770900,0.529890,216716,0.0,2,0.178575,-0.129856,0.975320,0.0,...,0.140784,-0.100923,0.984883,0.032887,0.0,0.0,0.176766,2,-0.004791,-0.100670

In [4]:
eye_data.columns

Index(['raw_timestamp', 'relative_to_video_first_frame_timestamp',
       'focus_distance', 'frame_number', 'stability', 'status',
       'gaze_forward_x', 'gaze_forward_y', 'gaze_forward_z', 'gaze_origin_x',
       'gaze_origin_y', 'gaze_origin_z', 'gaze_projected_to_left_view_x',
       'gaze_projected_to_left_view_y', 'gaze_projected_to_right_view_x',
       'gaze_projected_to_right_view_y', 'left_forward_x', 'left_forward_y',
       'left_forward_z', 'left_origin_x', 'left_origin_y', 'left_origin_z',
       'left_pupil_size', 'left_status', 'left_projected_x',
       'left_projected_y', 'right_forward_x', 'right_forward_y',
       'right_forward_z', 'right_origin_x', 'right_origin_y', 'right_origin_z',
       'right_pupil_size', 'right_status', 'right_projected_x',
       'right_projected_y'],
      dtype='object')

In [5]:
# Selecting specific columns needed for analysis
eye_data_imp_col = eye_data[['relative_to_video_first_frame_timestamp', 'gaze_projected_to_left_view_x', 
         'gaze_projected_to_left_view_y', 'gaze_projected_to_right_view_x', 
          'gaze_projected_to_right_view_y']]
eye_data_imp_col.head(5)

,relative_to_video_first_frame_timestamp,gaze_projected_to_left_view_x,gaze_projected_to_left_view_y,gaze_projected_to_right_view_x,gaze_projected_to_right_view_y
0,45677400,0.251052,-0.113030,-0.130023,-0.113171
1,55792600,0.322971,-0.122203,-0.057610,-0.122359
2,65776900,0.382257,-0.129396,0.001870,-0.129563
3,75821200,0.383979,-0.135997,0.003533,-0.136175
4,85770900,0.382913,-0.130616,0.002517,-0.130786

In [6]:
# Calculating the mean of the left and right eye view on the x & y coordinates respectively
xavg_column = eye_data_imp_col[['gaze_projected_to_left_view_x', 'gaze_projected_to_right_view_x']].mean(axis=1)
yavg_column = eye_data_imp_col[['gaze_projected_to_left_view_y', 'gaze_projected_to_right_view_y']].mean(axis=1)

# Adding the calculated values to the dataframe
eye_data_imp_col.insert(2, "xavg", xavg_column, True)
eye_data_imp_col.insert(6, "yavg", yavg_column, True)

eye_data_imp_col.head(5)

,relative_to_video_first_frame_timestamp,gaze_projected_to_left_view_x,xavg,gaze_projected_to_left_view_y,gaze_projected_to_right_view_x,gaze_projected_to_right_view_y,yavg
0,45677400,0.251052,0.060514,-0.113030,-0.130023,-0.113171,-0.113100
1,55792600,0.322971,0.132681,-0.122203,-0.057610,-0.122359,-0.122281
2,65776900,0.382257,0.192063,-0.129396,0.001870,-0.129563,-0.129480
3,75821200,0.383979,0.193756,-0.135997,0.003533,-0.136175,-0.136086
4,85770900,0.382913,0.192715,-0.130616,0.002517,-0.130786,-0.130701

In [7]:
# fig = plt.figure()
# ax = fig.add_subplot(111)
# fig.show()

In [8]:
# eye_data_imp_col.xavg
# car_sales["Doors"].mean()

In [9]:
# i = 0
# x, y = [], []

for i in range(10):
        # Append each number at the end of list
        sample_list.append(i)

In [10]:
df = pd.DataFrame({'country':['a','b','c','d'],
      'gdp':[1,2,3,4],
      'iso':['x','y','z','w']})
a_list = []

i = 0
while i < 3:
    a_list.extend(df['iso'].tolist())
    a_list.extend(df['country'].tolist())
    i += 1
    
print (a_list)

['x', 'y', 'z', 'w', 'a', 'b', 'c', 'd', 'x', 'y', 'z', 'w', 'a', 'b', 'c', 'd', 'x', 'y', 'z', 'w', 'a', 'b', 'c', 'd']